// Word pools for the Myth & Fantasy category. Data, not logic.
//
// Loaded LAZILY by src/subjects.js and never imported statically, which is the whole
// reason the catalog exists as a separate names-only module: the picker needs 600
// names, and a player needs the one category they chose. Keep it that way — a static
// import of this file anywhere in src/ would pull every word into the precached shell.
//
// Contract, enforced by tests/unit/content.test.js: 40+ words per subject, bare
// uppercase A-Z, 3-12 letters, no duplicates, and enough in every length bucket for
// both board presets to deal from. Short words are the scarce ones; write those first.
/** @type {Record<string,string>} */
export const WORDS = {
  'myth/dragons': 'JAW,EGG,ORE,GEM,FIRE,WING,CLAW,FANG,SCALE,HOARD,TALON,SMOKE,EMBER,SNOUT,SPIKE,GLIDE,WYVERN,CAVERN,MOLTEN,WINGED,CLAWED,BURROW,SPINES,FLYING,SERPENT,REPTILE,NOSTRIL,GLITTER,RAMPAGE,CRIMSON,SHIMMER,HATCHED,FIREBALL,SCORCHED,GUARDIAN,HOARDING,WINGSPAN,SULFUROUS,RAMPAGING,CAVERNOUS,MARAUDING,UNDERBELLY,SMOLDERING,INVINCIBLE,TERRITORIAL,MOUNTAINTOP,IMPENETRABLE,OVERPOWERING',
  'myth/wizards': 'ORB,HAT,HEX,OWL,WAND,ROBE,RUNE,CAPE,TOME,STAFF,CLOAK,MAGIC,CHARM,TOWER,ELDER,SPELL,MYSTIC,HOODED,ARCANE,WISDOM,AMULET,HERMIT,POTION,GOBLET,CONJURE,SORCERY,ALCHEMY,CRYSTAL,SCEPTER,ENCHANT,RITUALS,MAGICAL,GRIMOIRE,LEVITATE,TELEPORT,FAMILIAR,CAULDRON,DIVINING,SORCERER,SPELLBOOK,ENCHANTER,PARCHMENT,MOONSTONE,LEVITATION,APPRENTICE,DIVINATION,TRANSFIGURE,INCANTATION,PHILOSOPHER,SPELLCASTING',
  'myth/witches': 'HEX,HAT,CAT,JAR,BAT,BREW,BOIL,MOON,WART,BROOM,CLOAK,CRAFT,CURSE,COVEN,HERBS,RAVEN,SPELL,BUBBLE,CACKLE,WICKED,POTION,HEXING,BREWED,SPIDER,FLYING,MOONLIT,SORCERY,STIRRED,COBWEBS,HAGGARD,WHISKER,OMINOUS,GNARLED,CAULDRON,CACKLING,MIDNIGHT,FAMILIAR,GRIMOIRE,TATTERED,ENCHANTED,POISONOUS,SHRIVELED,SPELLCAST,BROOMSTICK,NIGHTSHADE,SPELLBOUND,TRANSFORMED,SHAPESHIFTED',
  'myth/castles': 'RAM,KEEP,MOAT,WALL,GATE,FLAG,ARCH,WARD,TOWER,SIEGE,GUARD,CROWN,VAULT,STONE,SPIRE,ARROW,TURRET,ARCHER,BATTLE,STABLE,CHAPEL,BAILEY,SHIELD,ARMORY,RAMPART,DUNGEON,MASONRY,GRANITE,HALLWAY,OUTPOST,ARCHWAY,PENNANT,FORTRESS,GARRISON,STOCKADE,TAPESTRY,SENTRIES,STAIRWAY,COURTYARD,GARGOYLES,CATAPULTS,FORTIFIED,GATEHOUSE,DRAWBRIDGE,BATTLEMENT,PORTCULLIS,STRONGHOLD,IMPENETRABLE',
  'myth/knights': 'AXE,FOE,HELM,DUEL,SPUR,OATH,MAIL,ARMS,LANCE,CREST,PLATE,HORSE,STEED,SWORD,ARMOR,JOUST,SHIELD,HELMET,SADDLE,BANNER,DAMSEL,CHARGE,GALLOP,SQUIRE,MOUNTED,TOURNEY,VALIANT,GALLANT,ARMORED,CHARGER,STIRRUP,BUCKLER,GAUNTLET,WARHORSE,CHIVALRY,SADDLERY,CHAINMAIL,SWORDSMAN,LONGSWORD,OATHBOUND,PROTECTOR,BROADSWORD,TOURNAMENT,VICTORIOUS,BATTLEFIELD,HORSEMANSHIP',
  'myth/pirates': 'SEA,MAP,OAR,RUM,KEG,SAIL,SHIP,CREW,MAST,DECK,HOOK,PLANK,SLOOP,CABIN,ROGUE,BOOTY,COAST,WAVES,CHEST,ANCHOR,GALLEY,PARROT,ISLAND,MUTINY,VOYAGE,RANSOM,HARBOR,CUTLASS,CAPTAIN,COMPASS,VOYAGER,SCUTTLE,MARINER,RIGGING,CANNONS,SCHOONER,STOWAWAY,EYEPATCH,SHIPYARD,PORTHOLE,MARAUDER,SEAWORTHY,BUCCANEER,NAVIGATOR,SHIPWRECK,PRIVATEER,FIGUREHEAD,CANNONBALL,QUARTERDECK,SWASHBUCKLER',
};
