// Word pools for the School category. Data, not logic.
//
// Loaded LAZILY by src/subjects.js and never imported statically, which is the whole
// reason the catalog exists as a separate names-only module: the picker needs 600
// names, and a player needs the one category they chose. Keep it that way — a static
// import of this file anywhere in src/ would pull every word into the precached shell.
//
// Contract, enforced by tests/unit/content.test.js: 40+ words per subject, bare
// uppercase A-Z, 3-12 letters, no duplicates, and enough in every length bucket for
// both board presets to deal from. Short words are the scarce ones; write those first.
/** @type {Record<string,string>} */
export const WORDS = {
  'school/classrooms': 'DESK,PEG,BIN,MAT,ROW,BELL,BOOK,GLUE,TAPE,WALL,DOOR,CHALK,CHAIR,CLOCK,SHELF,CHART,GLOBE,STOOL,RULER,BOARD,EASEL,MARKER,POSTER,CARPET,CRAYON,PENCIL,FOLDER,BINDER,WINDOW,TEACHER,STUDENT,CABINET,HALLWAY,LECTERN,CURTAIN,STAPLER,BOOKCASE,CALENDAR,BACKPACK,CUPBOARD,SCISSORS,BULLETIN,NOTEBOOK,BOOKSHELF,CUBBYHOLE,PROJECTOR,TIMETABLE,WHITEBOARD,CHALKBOARD,BLACKBOARD,SMARTBOARD,YARDSTICK,CLIPBOARD',
  'school/maths': 'SUM,ADD,MAX,MIN,TEN,ODD,AXIS,UNIT,PLUS,ZERO,HALF,MEAN,MODE,LINE,DIGIT,RATIO,GRAPH,TIMES,ANGLE,SHAPE,VALUE,EQUAL,TOTAL,MINUS,NUMBER,DIVIDE,DEGREE,FIGURE,SYMBOL,DOUBLE,SQUARE,CIRCLE,VOLUME,DECIMAL,FORMULA,PERCENT,AVERAGE,PROBLEM,COMPASS,ADDITION,SUBTRACT,TRIANGLE,EQUATION,FRACTION,GEOMETRY,ROUNDING,QUOTIENT,VARIABLE,MULTIPLY,SYMMETRY,SUBTRACTION,ARITHMETIC,CALCULATOR,PERCENTAGE,ESTIMATION,MEASUREMENT,DENOMINATOR,NUMERATOR,RECTANGLE,PROTRACTOR,GEOMETRIC',
  'school/spelling': 'BEE,PEN,WORD,RULE,ROOT,LIST,QUIZ,TEST,SOUND,VOWEL,RHYME,GUESS,CHECK,STUDY,DRILL,REVISE,LETTER,PREFIX,SUFFIX,MEMORY,SPOKEN,DICTATE,PATTERN,MISTAKE,CORRECT,WRITTEN,PHONICS,HOMONYM,ALPHABET,SYLLABLE,MEMORIZE,ACCURACY,MNEMONIC,DICTATION,PRONOUNCE,VOCABULARY,CONSONANT,DEFINITION,HOMOPHONE,PUNCTUATION,ABBREVIATION,CAPITALIZE,IRREGULAR',
  'school/playgrounds': 'TAG,RUN,HOP,MUD,FORT,SAND,BARS,JUMP,ROPE,SWING,SLIDE,CHASE,CLIMB,BENCH,FENCE,MULCH,SEESAW,TUNNEL,GRAVEL,LADDER,SPRING,ROCKER,RECESS,SANDBOX,CLIMBER,BALANCE,CLAMBER,CHASING,SWINGSET,SLIPPERY,CLIMBING,OBSTACLE,OVERHEAD,HOPSCOTCH,CARTWHEEL,TRAMPOLINE,TETHERBALL,ROUNDABOUT,FOURSQUARE,SANDCASTLE,DODGEBALL',
  'school/school-buses': 'BUS,SEAT,STOP,HORN,EXIT,LANE,RIDE,STEP,RAMP,AISLE,DRIVE,ROUTE,BOARD,BRAKE,WHEEL,ALARM,DRIVER,MIRROR,ENGINE,PICKUP,SIGNAL,WINDOW,BUCKLE,STATION,ROADWAY,DRIVING,TRANSIT,BOARDING,SCHEDULE,CROSSING,SEATBELT,FLASHING,EMERGENCY,PASSENGER,CROSSWALK,WINDSHIELD,STOPLIGHT,DISPATCHER,HEADLIGHT,TAILLIGHT,INTERSECTION',
  'school/homework': 'DUE,TASK,PLAN,READ,NOTE,QUIZ,TEST,DESK,LATE,ESSAY,STUDY,PAPER,DRAFT,SHEET,GRADE,REVISE,REPORT,ANSWER,PENCIL,FOLDER,PACKET,PROJECT,PLANNER,SUBJECT,CHAPTER,REWRITE,DEADLINE,REVISION,NOTEBOOK,EXERCISE,RESEARCH,REMINDER,FEEDBACK,TEXTBOOK,WORKSHEET,SUBMISSION,HANDWRITTEN,CORRECTION,GRADEBOOK,VOCABULARY,CALCULATION,PARAGRAPH',
  'school/exams': 'MARK,PASS,FAIL,TIME,QUIZ,TEST,PREP,CRAM,MOCK,ORAL,STUDY,PAPER,GRADE,SCORE,TIMER,ESSAY,RESULT,REVIEW,RETAKE,MARKER,ANSWER,REVISE,RETEST,PASSING,FAILING,TESTING,GRADING,PROCTOR,ANXIETY,OUTLINE,QUESTION,CRAMMING,REVISION,SCHEDULE,STOPWATCH,INVIGILATOR,CANDIDATE,CERTIFICATE,ASSESSMENT,CALCULATOR,PREPARATION,RESCHEDULE',
  'school/science-class': 'LENS,CELL,SEED,VOLT,WIRE,DATA,MASS,PLANT,GRAPH,PROBE,YEAST,LEVER,SCALE,FORCE,MAGNET,FOSSIL,ENERGY,INSECT,MOTION,PULLEY,PLANET,CIRCUIT,BATTERY,GRAVITY,HABITAT,SPECIES,MICROBE,DIAGRAM,GEOLOGY,MAGNETIC,ORGANISM,SKELETON,PENDULUM,ECOSYSTEM,TELESCOPE,DISSECTION,HYPOTHESIS,MICROSCOPE,EXPERIMENT,OBSERVATION,VERTEBRATE',
  'school/sports-day': 'RUN,RACE,LAP,WIN,TIE,BIB,HEAT,TEAM,FLAG,LANE,RELAY,MEDAL,TRACK,FIELD,BATON,CHEER,PODIUM,SPRINT,HURDLE,FINISH,RIBBON,TROPHY,RUNNER,WHISTLE,JAVELIN,STARTER,ATHLETE,CHAMPION,CHEERING,DISTANCE,OBSTACLE,TEAMWORK,OVERTAKE,STOPWATCH,SPECTATOR,ENDURANCE,COMPETITOR,QUALIFYING,PARTICIPANT,SPRINTING,SCOREBOARD',
  'school/assemblies': 'HALL,ROW,SING,CLAP,BOW,SEAT,HYMN,TUNE,TALK,STAGE,CHOIR,AWARD,MEDAL,STAND,VENUE,SPEECH,NOTICE,BANNER,CHORUS,SEATED,SILENT,PODIUM,ANTHEM,GATHER,PRESENT,WELCOME,OVATION,MORNING,MEETING,AUDIENCE,APPLAUSE,STANDING,GREETING,CEREMONY,MICROPHONE,CERTIFICATE,ANNOUNCEMENT,PRESENTATION,HEADTEACHER,SPOTLIGHT,PERFORMANCE,RECOGNITION',
  'school/school-trips': 'BUS,MAP,BAG,SEAT,STOP,SITE,TOUR,GUIDE,VISIT,COACH,LUNCH,BADGE,GROUP,SNACK,BUDDY,MUSEUM,PERMIT,LEADER,ROSTER,PICNIC,CAMERA,TICKET,GALLERY,EXHIBIT,JOURNEY,WALKING,PARKING,WEATHER,SOUVENIR,HISTORIC,SCHEDULE,BACKPACK,RAINCOAT,CHAPERONE,EXCURSION,HEADCOUNT,GUIDEBOOK,OVERNIGHT,ITINERARY,SUNSCREEN,SIGHTSEEING,DESTINATION',
  'school/stationery': 'PEN,INK,CLIP,TAPE,GLUE,TAB,PIN,GEL,PAD,CASE,RULER,CHALK,PAPER,LABEL,SHEET,STAMP,ERASER,CRAYON,STAPLE,PENCIL,FOLDER,MARKER,BINDER,MAGNET,NOTEPAD,STICKER,COMPASS,BOOKLET,GLITTER,SCISSORS,ENVELOPE,NOTEBOOK,CALENDAR,HIGHLIGHTER,SHARPENER,CLIPBOARD,CARTRIDGE,PAPERCLIP,CORRECTION,PROTRACTOR,WHITEBOARD',
};
