// node emit.mjs [--check] — writes the lazy icon modules the subject backgrounds import:
// src/backgrounds/icons.js (every icon a map uses, and which way the side-on ones face, from
// ../icons/facing.json) and subject-icons.js (the icon and motion maps).
// --check writes nothing and exits 1 when either file differs from what it would write.
import fs from 'node:fs';
const dir = new URL('.', import.meta.url).pathname;
const iconDir = new URL('../icons/', import.meta.url).pathname;
const out = new URL('../../../src/backgrounds/', import.meta.url).pathname;

/** @type {Map<string, string>} */
const svg = new Map();
for (const f of fs.readdirSync(iconDir).filter(f => /^part\d+\.json$/.test(f)))
  for (const it of JSON.parse(fs.readFileSync(iconDir + f, 'utf8'))) svg.set(it.id, it.svg);

const cats = fs.readdirSync(dir).filter(f => /^[a-z]+\.json$/.test(f) && f !== 'wishlist.json').sort();
// Subject motion: a motion per category, and per subject where another fits better.
/** @type {{categories:Record<string,string>, subjects:Record<string,string>}} */
const motion = JSON.parse(fs.readFileSync(dir + 'subject-motion.json', 'utf8'));
/** @param {Record<string,string>} o @returns {[string, string[]][]} */
const sorted = o => Object.entries(o).sort(([a], [b]) => (a < b ? -1 : 1)).map(([k, v]) => [k, [v]]);
/** @type {[string, string[]][]} */ const category = [];
/** @type {[string, string[]][]} */ const subject = [];
for (const f of cats) {
  const m = JSON.parse(fs.readFileSync(dir + f, 'utf8'));
  category.push([f.slice(0, -5), m.category]);
  for (const [k, v] of Object.entries(m.subjects).sort(([a], [b]) => (a < b ? -1 : 1))) subject.push([k, v]);
}
const used = new Set([...category, ...subject].flatMap(([, v]) => v));
const unknown = [...used].filter(id => !svg.has(id));
if (unknown.length) { console.error(`mapped but not drawn: ${unknown.join(', ')}`); process.exit(1); }
const ids = [...used].sort();
const quoted = ids.filter(id => /['\\\n]/.test(/** @type {string} */ (svg.get(id))));
if (quoted.length) { console.error(`cannot single-quote: ${quoted.join(', ')}`); process.exit(1); }
// Icons drawn side-on, which the motions mirror to face the way they move.
/** @type {{left:string[], right:string[]}} */
const facing = JSON.parse(fs.readFileSync(iconDir + 'facing.json', 'utf8'));
if (!Array.isArray(facing.left) || !Array.isArray(facing.right)) { console.error('icons/facing.json needs "left" and "right" lists'); process.exit(1); }
const undrawn = [...facing.left, ...facing.right].filter(id => !svg.has(id));
if (undrawn.length) { console.error(`icons/facing.json names icons not drawn: ${undrawn.join(', ')}`); process.exit(1); }
const both = facing.left.filter(id => facing.right.includes(id));
if (both.length) { console.error(`icons/facing.json lists these as both left and right: ${both.join(', ')}`); process.exit(1); }
const side = ids.filter(id => facing.left.includes(id) || facing.right.includes(id));

const head = '// Generated by tools/art-src/iconmap/emit.mjs; edit the sources there, not this file.\n';
const icons = `${head}// Inner markup for a 64x64 viewBox: classes t-a (main), t-b (shade), t-c (highlight), ln (stroke).

/** @type {Readonly<Record<string, string>>} */
export const ICONS = Object.freeze({
${ids.map(id => `  '${id}': '${svg.get(id)}',`).join('\n')}
});

// The icons drawn side-on: -1 faces left, 1 right. Any other faces front or is symmetric.

/** @type {Readonly<Record<string, number>>} */
export const FACING = Object.freeze({
${side.map(id => `  '${id}': ${facing.left.includes(id) ? -1 : 1},`).join('\n')}
});
`;
/** @param {[string, string[]][]} rows */
const table = rows => rows.map(([k, v]) => `  '${k}': '${v.join(' ')}',`).join('\n');
const maps = `${head}// Icon ids per category and per subject, space-separated, hero first.

/** @type {Readonly<Record<string, string>>} */
export const CATEGORY_ICONS = Object.freeze({
${table(category)}
});

/** @type {Readonly<Record<string, string>>} */
export const SUBJECT_ICONS = Object.freeze({
${table(subject)}
});

// Motion ids (subject-motion.js) per category, and per subject where another fits better.

/** @type {Readonly<Record<string, string>>} */
export const CATEGORY_MOTION = Object.freeze({
${table(sorted(motion.categories))}
});

/** @type {Readonly<Record<string, string>>} */
export const SUBJECT_MOTION = Object.freeze({
${table(sorted(motion.subjects))}
});
`;

let stale = 0;
for (const [name, text] of [['icons.js', icons], ['subject-icons.js', maps]]) {
  const now = fs.existsSync(out + name) ? fs.readFileSync(out + name, 'utf8') : '';
  if (now === text) continue;
  if (process.argv.includes('--check')) { console.error(`src/backgrounds/${name} is stale: run node tools/art-src/iconmap/emit.mjs`); stale++; }
  else fs.writeFileSync(out + name, text);
}
const unused = [...svg.keys()].filter(id => !used.has(id));
console.log(`${ids.length} icons, ${subject.length} subjects, ${category.length} categories` +
  (unused.length ? `; not mapped, so not emitted: ${unused.join(', ')}` : ''));
process.exit(stale ? 1 : 0);
